# anomalib==1.1.1
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  max_epochs: 500
  min_epochs: 100
  log_every_n_steps: 10
  enable_checkpointing: true
  enable_progress_bar: true

model:
  class_path: anomalib.models.Padim
  init_args:
    backbone: resnet18
    layers:
      - layer1
      - layer2
      - layer3
    pre_trained: true
    n_features: null

data:
  class_path: anomalib.data.MVTec
  init_args:
    root: /content/drive/MyDrive/Mvtec_dataset #Path to dataset
    category: bottle #If u want another category change it here then!
    train_batch_size: 4
    eval_batch_size: 4
    num_workers: 8
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5

normalization:
  normalization_method: MIN_MAX

task: SEGMENTATION

metrics:
  image:
    - F1Score
    - AUROC
  pixel: AUROC

logging:
  log_graph: false

default_root_dir: results
ckpt_path: null
